<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "aircraft".
 *
 * @property integer $id
 * @property string $rego
 * @property string $contest_id
 * @property string $manufacturer
 * @property string $model
 * @property string $serial
 * @property string $mctow
 * @property string $class
 * @property string $transponder
 * @property string $trailer
 * @property string $owner
 * @property string $location
 * @property string $annual_inspection_due
 * @property string $annual_airworthiness_due
 * @property string $radio_due
 * @property string $transponder_due
 * @property string $altimeter_due
 * @property integer $seats
 * @property integer $towplane
 * @property integer $self_launcher
 * @property integer $sustainer
 * @property integer $retractable
 * @property integer $vintage
 * @property integer $jet
 * @property integer $electric
 * @property string $created_at
 * @property string $updated_at
 * @property string $flarm
 * @property string $spot_feed_id
 * @property string $spot_esn
 * @property string $spot_active
 * @property string $particle_id
 * @property string $aliasModel
 */
abstract class Aircraft extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'aircraft';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rego', 'flarm', 'spot_feed_id', 'spot_esn', 'particle_id'], 'required'],
            [['annual_inspection_due', 'annual_airworthiness_due', 'radio_due', 'transponder_due', 'altimeter_due', 'created_at', 'updated_at', 'spot_active'], 'safe'],
            [['seats', 'towplane', 'self_launcher', 'sustainer', 'retractable', 'vintage', 'jet', 'electric'], 'integer'],
            [['rego', 'contest_id', 'manufacturer', 'model', 'serial', 'mctow', 'class', 'transponder', 'trailer', 'owner', 'location'], 'string', 'max' => 255],
            [['flarm'], 'string', 'max' => 6],
            [['spot_feed_id'], 'string', 'max' => 34],
            [['spot_esn'], 'string', 'max' => 18],
            [['particle_id'], 'string', 'max' => 24],
            [['rego'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'rego' => 'Rego',
            'contest_id' => 'Contest ID',
            'manufacturer' => 'Manufacturer',
            'model' => 'Model',
            'serial' => 'Serial',
            'mctow' => 'Mctow',
            'class' => 'Class',
            'transponder' => 'Transponder',
            'trailer' => 'Trailer',
            'owner' => 'Owner',
            'location' => 'Location',
            'annual_inspection_due' => 'Annual Inspection Due',
            'annual_airworthiness_due' => 'Annual Airworthiness Due',
            'radio_due' => 'Radio Due',
            'transponder_due' => 'Transponder Due',
            'altimeter_due' => 'Altimeter Due',
            'seats' => 'Seats',
            'towplane' => 'Towplane',
            'self_launcher' => 'Self Launcher',
            'sustainer' => 'Sustainer',
            'retractable' => 'Retractable',
            'vintage' => 'Vintage',
            'jet' => 'Jet',
            'electric' => 'Electric',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'flarm' => 'Flarm',
            'spot_feed_id' => 'Spot Feed ID',
            'spot_esn' => 'Spot Esn',
            'spot_active' => 'Spot Active',
            'particle_id' => 'Particle ID',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\AircraftQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\AircraftQuery(get_called_class());
    }


}
