<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "lists".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 *
 * @property \app\models\ListsWaypoints[] $listsWaypoints
 * @property \app\models\Waypoints[] $waypoints
 * @property string $aliasModel
 */
abstract class Lists extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lists';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description'], 'required'],
            [['name'], 'string', 'max' => 80],
            [['description'], 'string', 'max' => 140]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getListsWaypoints()
    {
        return $this->hasMany(\app\models\ListsWaypoints::className(), ['lists_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWaypoints()
    {
        return $this->hasMany(\app\models\Waypoints::className(), ['id' => 'waypoints_id'])->viaTable('lists_waypoints', ['lists_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\ListsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\ListsQuery(get_called_class());
    }


}
