<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "lists_waypoints".
 *
 * @property integer $lists_id
 * @property integer $waypoints_id
 * @property integer $owner
 *
 * @property \app\models\Lists $lists
 * @property \app\models\Waypoints $waypoints
 * @property string $aliasModel
 */
abstract class ListsWaypoints extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lists_waypoints';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['lists_id', 'waypoints_id'], 'required'],
            [['lists_id', 'waypoints_id', 'owner'], 'integer'],
            [['lists_id', 'waypoints_id'], 'unique', 'targetAttribute' => ['lists_id', 'waypoints_id']],
            [['lists_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Lists::className(), 'targetAttribute' => ['lists_id' => 'id']],
            [['waypoints_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Waypoints::className(), 'targetAttribute' => ['waypoints_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'lists_id' => 'Lists ID',
            'waypoints_id' => 'Waypoints ID',
            'owner' => 'Owner',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLists()
    {
        return $this->hasOne(\app\models\Lists::className(), ['id' => 'lists_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWaypoints()
    {
        return $this->hasOne(\app\models\Waypoints::className(), ['id' => 'waypoints_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\ListsWaypointsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\ListsWaypointsQuery(get_called_class());
    }


}
