<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "waypoints".
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property string $country
 * @property string $lat
 * @property string $lon
 * @property integer $elevation
 * @property integer $style
 * @property string $direction
 * @property integer $length
 * @property string $frequency
 * @property string $description
 * @property integer $number
 * @property integer $batch
 * @property string $created_at
 * @property string $updated_at
 * @property string $location
 *
 * @property \app\models\ListsWaypoints[] $listsWaypoints
 * @property \app\models\Lists[] $lists
 * @property string $aliasModel
 */
abstract class Waypoints extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'waypoints';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['lat', 'lon'], 'number'],
            [['elevation', 'style', 'length', 'number', 'batch'], 'integer'],
            [['description', 'location'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['name', 'code', 'country', 'direction', 'frequency'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'code' => 'Code',
            'country' => 'Country',
            'lat' => 'Lat',
            'lon' => 'Lon',
            'elevation' => 'Elevation',
            'style' => 'Style',
            'direction' => 'Direction',
            'length' => 'Length',
            'frequency' => 'Frequency',
            'description' => 'Description',
            'number' => 'Number',
            'batch' => 'Batch',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'location' => 'Location',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getListsWaypoints()
    {
        return $this->hasMany(\app\models\ListsWaypoints::className(), ['waypoints_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLists()
    {
        return $this->hasMany(\app\models\Lists::className(), ['id' => 'lists_id'])->viaTable('lists_waypoints', ['waypoints_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\WaypointsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\WaypointsQuery(get_called_class());
    }


}
