<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\contest\models\base;

use Yii;

/**
 * This is the base-model class for table "classes".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property array $metadata
 *
 * @property \app\modules\contest\models\Entries[] $entries
 * @property string $aliasModel
 */
abstract class Classes extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'classes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description'], 'required'],
            [['description'], 'string'],
            [['metadata'], 'safe'],
            [['name'], 'string', 'max' => 140]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'metadata' => 'Additional Information',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'name' => 'Name',
            'description' => 'Description',
            'metadata' => 'Additional Information',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEntries()
    {
        return $this->hasMany(\app\modules\contest\models\Entries::className(), ['classes_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\modules\contest\models\ClassesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\modules\contest\models\ClassesQuery(get_called_class());
    }


}
