<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\contest\models\base;

use Yii;

/**
 * This is the base-model class for table "contests".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $start
 * @property string $end
 * @property array $metadata
 *
 * @property \app\modules\contest\models\Entries[] $entries
 * @property string $aliasModel
 */
abstract class Contests extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'contests';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description', 'start', 'end'], 'required'],
            [['description'], 'string'],
            [['start', 'end', 'metadata'], 'safe'],
            [['name'], 'string', 'max' => 140]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Primary Key',
            'name' => 'Name',
            'description' => 'Description',
            'start' => 'Start Date',
            'end' => 'End Date',
            'metadata' => 'Additional Information',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'id' => 'Primary Key',
            'name' => 'Name',
            'description' => 'Description',
            'start' => 'Start Date',
            'end' => 'End Date',
            'metadata' => 'Additional Information',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEntries()
    {
        return $this->hasMany(\app\modules\contest\models\Entries::className(), ['contest_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\modules\contest\models\ContestsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\modules\contest\models\ContestsQuery(get_called_class());
    }


}
